CREATE TABLE `COMPANY_MASTER` (
  `COMPANY_CD` varchar(11) NOT NULL DEFAULT '',
  `COMPANY_NAME` varchar(100) DEFAULT NULL,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`COMPANY_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;